import type { Metadata } from "next";
import { LegalPage, LegalSection } from "../../components/LegalPage";

export const metadata: Metadata = { title: "Conditions du pilote gratuit", description: "Conditions d’utilisation de Kivli pendant sa phase pilote gratuite.", robots: { index: true, follow: true } };

export default function ConditionsPilotePage() {
  return <LegalPage eyebrow="Cadre contractuel" title="Conditions du pilote gratuit" intro="Ces conditions encadrent l’accès professionnel à Kivli avant son éventuelle commercialisation. Elles ne constituent pas des CGV payantes." version="26 août 2026">
    <LegalSection title="1. Objet et acceptation"><p>Kivli met à disposition des commerces et professionnels un outil de fidélité digitale comprenant notamment la création d’un programme, des cartes clients, la gestion des points et récompenses, des accès employés et un historique. L’accès aux fonctions impliquant les données des clients est activé lorsque le propriétaire authentifié confirme être habilité à engager le commerce et accepte expressément les présentes conditions ainsi que l’<a href="/accord-traitement-donnees">annexe RGPD</a>.</p></LegalSection>
    <LegalSection title="2. Pilote entièrement gratuit"><p>Le pilote est fourni gratuitement pendant une durée indicative de 6 à 8 semaines à compter de son activation. Aucun moyen de paiement n’est demandé, aucun prélèvement n’est réalisé, aucun renouvellement payant ou automatique n’est prévu et aucune obligation d’achat n’est créée. Toute future offre payante fera l’objet d’une information et d’un accord distincts ; l’absence de réponse ne pourra jamais valoir souscription.</p></LegalSection>
    <LegalSection title="3. Accès au service"><p>Le commerçant fournit des informations exactes, protège son code confidentiel, limite les accès employés aux personnes autorisées et signale rapidement tout usage suspect. Il reste responsable des appareils et réseaux utilisés pour accéder à Kivli.</p></LegalSection>
    <LegalSection title="4. Responsabilité du programme"><p>Le commerçant définit les règles de son programme, les conditions d’attribution des points et les récompenses promises. Il s’engage à présenter ces règles clairement, à honorer les récompenses valablement acquises, à corriger les erreurs et à respecter le droit applicable à son activité. Kivli fournit l’outil technique mais n’est ni le vendeur des produits du commerçant ni le débiteur des récompenses.</p></LegalSection>
    <LegalSection title="5. Données des clients"><p>Le commerçant est responsable des traitements liés à son programme. Il doit informer ses clients, n’utiliser leurs données que pour les finalités annoncées, traiter leurs demandes de droits et ne prospecter par SMS que sur la base d’un accord valable. Kivli agit comme sous-traitant selon l’<a href="/accord-traitement-donnees">annexe de traitement des données</a>.</p></LegalSection>
    <LegalSection title="6. Disponibilité et évolutions"><p>Le pilote sert à tester et améliorer Kivli. Des opérations de maintenance ou des anomalies peuvent temporairement affecter le service. Kivli met en œuvre des moyens raisonnables pour préserver la continuité, la sécurité et les données, sans garantir une disponibilité absolue. Les fonctions essentielles ne seront pas volontairement retirées sans information préalable raisonnable, sauf urgence de sécurité ou obligation légale.</p></LegalSection>
    <LegalSection title="7. Retours et contenus"><p>Les idées et retours peuvent être utilisés pour améliorer Kivli sans transférer au service les droits portant sur les marques, contenus ou données du commerçant. Le commerçant garantit disposer des droits nécessaires sur les textes et éléments qu’il renseigne.</p></LegalSection>
    <LegalSection title="8. Fin du pilote et réversibilité"><p>Le commerçant peut quitter le pilote à tout moment en écrivant à <a href="mailto:contact@kivli.fr?subject=Fin%20du%20pilote%20Kivli">contact@kivli.fr</a>. Kivli peut mettre fin au pilote avec un préavis raisonnable de 30 jours, sauf sécurité, usage illicite ou impossibilité majeure. Sur demande reçue avant la fermeture, Kivli fournit une restitution exploitable des données du commerce dans un format courant. Les données opérationnelles sont ensuite supprimées dans les 30 jours, hors éléments dont la conservation limitée est nécessaire à une obligation ou à la défense de droits.</p></LegalSection>
    <LegalSection title="9. Responsabilité"><p>Chaque partie répond des dommages directs causés par ses fautes ou manquements. Compte tenu du caractère gratuit et expérimental du pilote, Kivli ne répond pas des pertes indirectes ni des décisions commerciales prises uniquement à partir des indicateurs du service. Cette limitation ne s’applique pas en cas de faute lourde, dol, atteinte aux données personnelles imputable à Kivli ou lorsqu’une règle impérative l’interdit.</p></LegalSection>
    <LegalSection title="10. Droit applicable et contact"><p>Les présentes conditions sont soumises au droit français. En cas de difficulté, les parties cherchent d’abord une solution amiable en écrivant à <a href="mailto:contact@kivli.fr">contact@kivli.fr</a>. Les règles impératives de compétence restent applicables.</p></LegalSection>
  </LegalPage>;
}
