import type { Metadata } from "next";
import { LegalPage, LegalSection } from "../../components/LegalPage";

export const metadata: Metadata = { title: "Annexe RGPD — sous-traitance", description: "Clauses de traitement des données entre Kivli et les commerçants.", robots: { index: true, follow: true } };

export default function AccordTraitementPage() {
  return <LegalPage eyebrow="Article 28 du RGPD" title="Annexe de traitement des données" intro="Cette annexe fait partie des conditions du pilote et encadre les traitements réalisés par Kivli pour le compte du commerçant.">
    <LegalSection title="1. Parties et rôles"><p>Le commerçant utilisant Kivli est le <strong>responsable du traitement</strong> des données de ses clients et employés. TAILEB Ouahid, éditeur de Kivli, est le <strong>sous-traitant</strong> pour l’hébergement et l’exploitation technique de ces données. Kivli reste responsable de ses traitements propres liés aux comptes, à la sécurité, au support et à l’administration du pilote.</p></LegalSection>
    <LegalSection title="2. Description du traitement"><div className="legal-table-wrap"><table><tbody><tr><th>Objet</th><td>Fourniture d’une plateforme de fidélité digitale.</td></tr><tr><th>Durée</th><td>Durée du compte et période nécessaire à la restitution puis à la suppression.</td></tr><tr><th>Opérations</th><td>Collecte, normalisation, enregistrement, consultation, organisation, calcul des points, génération de QR codes, modification, export, limitation et suppression.</td></tr><tr><th>Finalités</th><td>Inscription aux programmes, gestion des cartes, passages ou achats, points, récompenses, historique, accès employés et, uniquement sur instruction valable, campagnes SMS futures.</td></tr><tr><th>Personnes</th><td>Clients du commerce, propriétaire et employés autorisés.</td></tr><tr><th>Données</th><td>Prénom, téléphone, consentement marketing et sa preuve, identifiant de carte, activité de fidélité, récompenses, historique ; identité et accès limités des employés.</td></tr></tbody></table></div></LegalSection>
    <LegalSection title="3. Instructions documentées"><p>Kivli traite les données uniquement pour fournir les fonctions activées par le commerçant, selon les présentes conditions et les actions effectuées dans l’interface. Toute demande supplémentaire doit être formulée par écrit. Kivli informe le commerçant si une instruction paraît contraire au RGPD ou au droit applicable, sauf interdiction légale.</p></LegalSection>
    <LegalSection title="4. Engagements de Kivli"><ul><li>garantir la confidentialité des personnes autorisées ;</li><li>mettre en œuvre les mesures de sécurité décrites ci-dessous ;</li><li>aider le commerçant à répondre aux demandes d’accès, rectification, effacement, limitation, opposition et portabilité ;</li><li>assister le commerçant pour la sécurité, les analyses nécessaires et les violations de données ;</li><li>notifier toute violation concernant ses données dans les meilleurs délais après en avoir pris connaissance, avec les informations disponibles ;</li><li>tenir à disposition les informations nécessaires pour démontrer la conformité et permettre un audit raisonnable, sans compromettre la sécurité d’autres utilisateurs ;</li><li>supprimer ou restituer les données en fin de service selon le choix du commerçant, sauf obligation légale contraire.</li></ul></LegalSection>
    <LegalSection title="5. Engagements du commerçant"><ul><li>collecter et traiter les données de façon licite, loyale et transparente ;</li><li>fournir aux clients les informations requises et définir des durées adaptées ;</li><li>ne demander que les données nécessaires ;</li><li>gérer les droits et vérifier l’identité du demandeur de façon proportionnée ;</li><li>réserver la prospection SMS aux personnes ayant valablement consenti et respecter tout retrait ;</li><li>sécuriser ses accès et ceux de ses employés ;</li><li>documenter ses instructions et superviser le traitement.</li></ul></LegalSection>
    <LegalSection title="6. Mesures de sécurité"><p>HTTPS, contrôle d’accès par rôle, secrets hachés avec sel, cookies HTTP-only et sécurisés, limitation des tentatives, vérification d’e-mail, identifiants uniques, séparation des espaces, journalisation des opérations sensibles, restriction des employés, base D1 de juridiction européenne et procédures de suppression. Ces mesures évoluent selon les risques et l’état de l’art.</p></LegalSection>
    <LegalSection title="7. Sous-traitants ultérieurs et transferts"><p>Le commerçant autorise de manière générale le recours à <strong>Cloudflare, Inc.</strong> pour Workers, D1, diffusion et sécurité, et à <strong>OVH SAS</strong> pour la messagerie Zimbra. La base D1 persiste dans l’Union européenne ; le réseau mondial de Cloudflare peut traiter des requêtes et métadonnées hors EEE selon son accord de traitement et ses garanties de transfert. OVHcloud héberge la messagerie Zimbra utilisée par Kivli en France.</p><p>Kivli informe les commerçants de tout ajout ou remplacement important au moins 30 jours avant sa prise d’effet lorsque cela est possible. Le commerçant peut présenter une objection motivée liée à la protection des données ; les parties cherchent alors une solution raisonnable.</p></LegalSection>
    <LegalSection title="8. Sort des données"><p>À la fin du pilote, le commerçant peut demander une restitution dans un format structuré courant. Après restitution ou expiration du délai prévu, Kivli supprime les données opérationnelles et leurs copies contrôlées dans les 30 jours, sous réserve des sauvegardes à rotation limitée et des données qu’une obligation légale impose de conserver. Les données clients inactives sont supprimées au plus tard trois ans après leur dernière activité.</p></LegalSection>
    <LegalSection title="9. Exercice des droits et contact"><p>Les demandes adressées directement à Kivli sont transmises au commerçant concerné. Kivli fournit l’assistance technique raisonnable nécessaire dans les délais permettant au commerçant de répondre sous un mois. Contact : <a href="mailto:contact@kivli.fr">contact@kivli.fr</a>.</p></LegalSection>
  </LegalPage>;
}
