import type { Metadata } from "next";
import { LegalPage, LegalSection } from "../../components/LegalPage";

export const metadata: Metadata = { title: "Politique de confidentialité", description: "Comment Kivli protège les données des commerçants, équipes et clients.", robots: { index: true, follow: true } };

export default function ConfidentialitePage() {
  return <LegalPage eyebrow="Données personnelles" title="Politique de confidentialité" intro="Cette politique décrit les traitements réellement effectués par Kivli pendant sa phase pilote gratuite.">
    <LegalSection title="1. Qui traite les données ?">
      <p><strong>Pour les comptes commerçants et l’administration de Kivli</strong>, TAILEB Ouahid, éditeur de Kivli, est responsable du traitement. Contact : <a href="mailto:contact@kivli.fr">contact@kivli.fr</a>, 2 rue Léonie, 28100 Dreux.</p>
      <p><strong>Pour les cartes de fidélité des clients</strong>, le commerce qui propose le programme décide de ses finalités et en est le responsable du traitement. Kivli héberge et traite ces données pour son compte en qualité de sous-traitant. Les obligations correspondantes sont précisées dans l’<a href="/accord-traitement-donnees">annexe RGPD</a>.</p>
    </LegalSection>
    <LegalSection title="2. Données, finalités, bases légales et durées">
      <div className="legal-table-wrap legal-data-table"><table><thead><tr><th>Personnes et données</th><th>Pourquoi et base légale</th><th>Durée principale</th></tr></thead><tbody>
        <tr><td data-label="Personnes et données"><strong>Commerçants</strong><br/>Identité, commerce, e-mail, téléphone facultatif, empreinte du code confidentiel, vérification d’e-mail, programme, retours et activité.</td><td data-label="Pourquoi et base légale">Créer, sécuriser et administrer le compte ; fournir le pilote ; répondre au support. Exécution des conditions du pilote et intérêt légitime de sécurité et d’amélioration du service.</td><td data-label="Durée principale">Pendant le compte. Suppression opérationnelle dans les 30 jours suivant la fin ou une demande valable ; éléments strictement nécessaires à la preuve et aux litiges conservés en accès restreint jusqu’à 5 ans.</td></tr>
        <tr><td data-label="Personnes et données"><strong>Employés</strong><br/>Nom affiché, e-mail facultatif, identifiant, empreinte du PIN, statut et actions réalisées.</td><td data-label="Pourquoi et base légale">Fournir les accès demandés par le commerçant et tracer les opérations. Traitement effectué pour le compte du commerçant.</td><td data-label="Durée principale">Pendant l’activation du compte employé, puis suppression avec le commerce ou sur instruction de celui-ci.</td></tr>
        <tr><td data-label="Personnes et données"><strong>Clients fidélité</strong><br/>Prénom, téléphone, identifiant de carte, points, achats ou passages, récompenses et historique.</td><td data-label="Pourquoi et base légale">Créer et faire fonctionner la carte demandée. Exécution du programme de fidélité sous la responsabilité du commerce.</td><td data-label="Durée principale">Pendant l’utilisation du programme, puis au plus tard 3 ans après la dernière activité, sauf demande d’effacement antérieure ou obligation justifiée.</td></tr>
        <tr><td data-label="Personnes et données"><strong>Choix SMS</strong><br/>Accord ou refus, date, version de la mention, source et retrait.</td><td data-label="Pourquoi et base légale">Permettre au commerce d’envoyer ultérieurement ses offres. Consentement distinct, facultatif et révocable.</td><td data-label="Durée principale">Pendant la relation puis 3 ans. La preuve d’un retrait peut être conservée 3 ans dans une liste d’opposition utilisée uniquement pour éviter une nouvelle sollicitation.</td></tr>
        <tr><td data-label="Personnes et données"><strong>Sécurité et technique</strong><br/>Sessions hachées, tentatives de connexion, journaux d’événements et données techniques limitées telles que l’adresse IP chez l’hébergeur.</td><td data-label="Pourquoi et base légale">Authentification, prévention des abus, diagnostic et sécurité. Intérêt légitime.</td><td data-label="Durée principale">Sessions commerçants : 30 jours maximum ; session admin : 12 heures ; tentatives et journaux applicatifs : jusqu’à 12 mois selon leur utilité de sécurité.</td></tr>
      </tbody></table></div>
      <p>Les champs obligatoires sont signalés dans les formulaires. Sans prénom et numéro de téléphone, la carte ne peut pas être créée. Le téléphone sert à identifier et retrouver la carte ; il n’autorise jamais, à lui seul, l’envoi de publicité.</p>
    </LegalSection>
    <LegalSection title="3. SMS commerciaux et retrait du consentement">
      <p>La case SMS est séparée, facultative et décochée par défaut. Un refus n’empêche pas la création de la carte. Aucun SMS commercial n’est actuellement envoyé par Kivli. Si cette fonction est activée ultérieurement, le commerce devra s’identifier dans chaque message et proposer un moyen simple et gratuit de se désinscrire.</p>
      <p>Le client peut retirer son accord depuis sa carte Kivli ou écrire à <a href="mailto:contact@kivli.fr?subject=Retrait%20consentement%20SMS">contact@kivli.fr</a>. Le retrait ne supprime pas la carte : il arrête uniquement l’usage marketing du numéro.</p>
    </LegalSection>
    <LegalSection title="4. Destinataires et prestataires">
      <ul><li>Le commerçant responsable et, dans les limites de leurs droits, ses employés autorisés.</li><li>L’éditeur de Kivli lorsqu’un accès est nécessaire à l’exploitation, au support ou à la sécurité.</li><li><strong>Cloudflare</strong> : Workers, sécurité, diffusion et base D1. Les données persistantes D1 sont stockées dans la juridiction Union européenne. Les requêtes peuvent être traitées sur le réseau mondial de Cloudflare et certaines métadonnées techniques peuvent être traitées dans l’EEE ou aux États-Unis, sous les garanties contractuelles de Cloudflare.</li><li><strong>OVHcloud</strong> : nom de domaine et messagerie Zimbra utilisée pour les e-mails de confirmation, de support et les demandes RGPD ; la messagerie est hébergée dans des centres de données français.</li></ul>
      <p>Kivli ne vend pas les données et ne les transmet pas à des régies publicitaires. La liste des sous-traitants peut évoluer ; tout changement important sera signalé aux commerçants conformément à l’annexe RGPD.</p>
    </LegalSection>
    <LegalSection id="cookies" title="5. Cookies, stockage local et PWA">
      <p>Kivli n’utilise actuellement aucun outil publicitaire ni outil de mesure d’audience. Il n’existe donc pas de bannière de consentement.</p>
      <ul><li><code>kivli_session</code> : cookie sécurisé, HTTP-only et strictement nécessaire à la connexion du commerçant ou de l’employé, valable au maximum 30 jours.</li><li><code>__Host-kivli_admin</code> : cookie strictement nécessaire à l’administration, valable au maximum 12 heures.</li><li><code>kivli-card-…</code> : stockage local conservant uniquement le code de la carte sur l’appareil du client afin de la retrouver.</li><li>Le service worker Kivli met en cache le socle public de l’application pour améliorer son ouverture ; les réponses des API ne sont pas mises en cache par ce mécanisme.</li></ul>
      <p>Ces mécanismes sont nécessaires au service demandé et ne servent ni au profilage ni à la publicité. Une bannière sera ajoutée avant tout futur traceur soumis au consentement.</p>
    </LegalSection>
    <LegalSection title="6. Vos droits">
      <p>Selon le traitement, vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition et la portabilité de vos données, ou retirer un consentement à tout moment. Écrivez à <a href="mailto:contact@kivli.fr?subject=Exercice%20de%20mes%20droits%20RGPD">contact@kivli.fr</a> en indiquant le commerce et les informations nécessaires pour retrouver votre compte ou votre carte. Une preuve d’identité ne sera demandée qu’en cas de doute raisonnable.</p>
      <p>La demande est traitée dans les meilleurs délais et en principe sous un mois. Pour les données d’une carte, Kivli transmet la demande au commerce responsable et l’assiste techniquement. Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes" rel="noreferrer">CNIL</a>.</p>
    </LegalSection>
    <LegalSection title="7. Sécurité et violations"><p>Kivli utilise HTTPS, des secrets hachés, des cookies sécurisés et HTTP-only, une séparation des rôles, des accès employés limités, une base D1 de juridiction européenne et une journalisation des actions sensibles. En cas de violation, Kivli informe les commerçants concernés dans les meilleurs délais afin qu’ils puissent respecter leurs propres obligations, notamment l’éventuelle notification à la CNIL sous 72 heures.</p></LegalSection>
    <LegalSection title="8. Mise à jour"><p>Cette politique peut évoluer avec le pilote. Les changements importants affectant les traitements ou les droits seront portés à la connaissance des commerçants avant leur prise d’effet.</p></LegalSection>
  </LegalPage>;
}
